name:           Apache Struts
markdown:       kramdown
markdown_ext:   md
source:         source
encoding:       UTF-8
highlighter:    rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..3

# Simplifies introducing changes related to the latest release
current_version: 6.6.1
current_version_short: 661
current_25x_version: 2.5.33
prev_version: 6.6.0
prev_version_short: 660
prev_25_version: 2.5.33
release_date: 18 October 2024
prev_release_date: 10 August 2024
prev_25_release_date: 7 December 2023
release_date_short: 20241018
prev_release_date_short: 20240810
prev_25_release_date_short: 20231207-2

beta_release_date_short: 20160126

archetype_version: 6.0.0

# Allows directly edit pages on GitHub
repository_url: https://github.com/apache/struts-site

# Used to generate links to Struts Core ApiDocs
apidocs: /maven/struts2-core/apidocs

# Confluence main site
wiki_url: https://cwiki.apache.org/confluence/display/WW

# Archive site with all the versions
archive_url: https://archive.apache.org/dist/struts/

# JIRA issue tracking
jira_url: https://issues.apache.org/jira/projects/WW/
